### ISSUE TITLE
Access Error in cs_log

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#227]
Full Error from the cs_log:
```
[2021-11-08 18:27:17.399] [INFO]: init error: The process cannot access the file 'F:\Ori\Ori and the Will of the Wisps Randomizer\randomizer\cs_log.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at RandoMainDLL.Msg.Init()
   at RandoMainDLL.Randomizer.Initialize()
```

(yes, this is written into cs_log)

**Comment by timoschwarzer** [comment]
I love Windows

**Comment by MunWolf** [comment]
This is due to us having the file open in a logging thread and trying to open it again on the main thread, fix is to move all of the logging to the logging thread.
